const education = [
  {
    school: "University of Communications",
    degree: "Bachelor of Communications",
    period: "2016 – 2020",
    description: "Focus on media studies and strategic communications.",
  },
  {
    school: "Professional Development Institute",
    degree: "Digital Marketing Certificate",
    period: "2021",
    description: "Content strategy, social media, and analytics.",
  },
];

const experience = [
  {
    role: "Communications Officer",
    company: "International NGO",
    period: "2022 – Present",
    description:
      "Lead internal and external communications, manage social media, and coordinate events. Draft press releases and maintain brand consistency.",
  },
  {
    role: "Communications Coordinator",
    company: "Regional Nonprofit",
    period: "2020 – 2022",
    description:
      "Supported campaigns, wrote newsletters, and managed community outreach. Improved engagement metrics by 40%.",
  },
  {
    role: "Marketing Intern",
    company: "Creative Agency",
    period: "2019 – 2020",
    description:
      "Assisted with content creation, social scheduling, and client reporting.",
  },
];

const skills = [
  { name: "Strategic Communications", level: "Expert" },
  { name: "Social Media Management", level: "Expert" },
  { name: "Content Writing & Editing", level: "Expert" },
  { name: "Event Coordination", level: "Advanced" },
  { name: "Brand Management", level: "Advanced" },
  { name: "Project Management", level: "Advanced" },
  { name: "Adobe Creative Suite", level: "Intermediate" },
  { name: "Data & Analytics", level: "Intermediate" },
];

export const metadata = {
  title: "Nguyễn Thu Huệ",
  description: "Portfolio of Nguyễn Thu Huệ",
  icons: {
    icon: "/images/logo.webp",
  }
};

const PortfolioPage = () => {
  return (
    <div className="pt-24 pb-20 bg-white">
      <div className="container mx-auto px-4 max-w-3xl">
        {/* Page title */}
        <section className="mb-16 text-center">
          <h1 className="text-4xl font-bold mb-4">Portfolio</h1>
          <p className="text-gray-500 text-lg">
            This is a sample page generated by AI. Content will be updated soon.
          </p>
        </section>

        {/* Education */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold text-pink-500 mb-6 border-b border-zinc-200 pb-2">
            Education
          </h2>
          <ul className="space-y-8">
            {education.map((item, i) => (
              <li key={i} className="pl-0">
                <div className="flex flex-col sm:flex-row sm:justify-between sm:items-baseline gap-1">
                  <h3 className="text-lg font-semibold">{item.school}</h3>
                  <span className="text-sm text-gray-500">{item.period}</span>
                </div>
                <p className="text-pink-500/90 font-medium mt-1">{item.degree}</p>
                <p className="text-gray-600 mt-2">{item.description}</p>
              </li>
            ))}
          </ul>
        </section>

        {/* Experience */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold text-pink-500 mb-6 border-b border-zinc-200 pb-2">
            Experience
          </h2>
          <ul className="space-y-8">
            {experience.map((item, i) => (
              <li key={i}>
                <div className="flex flex-col sm:flex-row sm:justify-between sm:items-baseline gap-1">
                  <h3 className="text-lg font-semibold">{item.role}</h3>
                  <span className="text-sm text-gray-500">{item.period}</span>
                </div>
                <p className="text-pink-500/90 font-medium mt-1">{item.company}</p>
                <p className="text-gray-600 mt-2">{item.description}</p>
              </li>
            ))}
          </ul>
        </section>

        {/* Skills */}
        <section>
          <h2 className="text-2xl font-bold text-pink-500 mb-6 border-b border-zinc-200 pb-2">
            Skills
          </h2>
          <ul className="flex flex-wrap gap-3">
            {skills.map((skill, i) => (
              <li
                key={i}
                className="px-4 py-2 rounded-md border border-zinc-200 bg-white hover:border-pink-500 hover:bg-pink-50/50 transition-colors duration-300"
              >
                <span className="font-medium">{skill.name}</span>
                <span className="text-gray-500 text-sm ml-2">({skill.level})</span>
              </li>
            ))}
          </ul>
        </section>
      </div>
    </div>
  );
};

export default PortfolioPage;
